# Generated by Django 4.2.16 on 2026-04-03 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='website.semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('search_keywords', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='website.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('student_helpful_count', models.IntegerField(default=0)),
                ('student_not_helpful_count', models.IntegerField(default=0)),
                ('ml_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.topic')),
            ],
            options={
                'ordering': ['-ml_score'],
            },
        ),
        migrations.CreateModel(
            name='ReadingResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Textbook'), ('blog', 'Blog Article'), ('notes', 'Study Notes'), ('article', 'Article')], max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('view_count', models.IntegerField(default=0)),
                ('student_helpful_count', models.IntegerField(default=0)),
                ('student_not_helpful_count', models.IntegerField(default=0)),
                ('ml_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='website.topic')),
            ],
            options={
                'ordering': ['-ml_score'],
            },
        ),
        migrations.CreateModel(
            name='StudentInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading')], max_length=20)),
                ('resource_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('bookmark', 'Bookmark'), ('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('view', 'Viewed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='website.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session_key', 'topic', 'resource_type', 'resource_id', 'interaction_type')},
            },
        ),
    ]
