"""Integration and feature tests for the Topiq project."""

from __future__ import annotations

import json
from unittest.mock import patch

from django.core.management import call_command
from django.test import Client, TestCase

from website.models import (
    ReadingResource,
    Semester,
    StudentInteraction,
    Subject,
    Topic,
    VideoResource,
)
from website.recommender import ResourceRecommender, search_topics


class BaseTopiqTestCase(TestCase):
    """Shared fixture creation helpers for Topiq tests."""

    def setUp(self):
        """Create a reusable subject/topic/resource graph for tests."""
        self.client = Client()
        self.semester = Semester.objects.create(name="5th Semester", order=5)
        self.subject = Subject.objects.create(
            semester=self.semester,
            name="Operating System",
            code="CS301",
            description="Operating system fundamentals.",
        )
        self.deadlock_topic = Topic.objects.create(
            subject=self.subject,
            name="Deadlock",
            description="Deadlock concepts and resource allocation.",
            tags="deadlock, coffman conditions, banker algorithm, mutual exclusion",
            search_keywords="dead lock banker algorithm circular wait",
        )
        self.binary_tree_topic = Topic.objects.create(
            subject=Subject.objects.create(
                semester=Semester.objects.create(name="3rd Semester", order=3),
                name="Data Structures",
                code="CS201",
                description="Data structures course.",
            ),
            name="Binary Tree",
            description="Binary trees and traversals.",
            tags="binary tree, bst, tree traversal",
            search_keywords="tree data structure binary search tree",
        )
        self._create_resources_for_topic(self.deadlock_topic)
        self._create_resources_for_topic(self.binary_tree_topic)

    def _create_resources_for_topic(self, topic: Topic):
        """Create three videos and three readings for the given topic."""
        for index, difficulty in enumerate(["beginner", "intermediate", "advanced"], start=1):
            VideoResource.objects.create(
                topic=topic,
                title=f"{topic.name} Video {index}",
                description=f"{topic.name} video explanation {index}",
                youtube_url=f"https://youtube.com/watch?v={slug_fragment(topic.name)}v{index}",
                duration=f"{10 + index}:0{index}",
                duration_seconds=(10 + index) * 60 + index,
                difficulty_level=difficulty,
                view_count=100000 * index,
                rating=4.2 + (index * 0.1),
                student_helpful_count=10 * index,
                student_not_helpful_count=index,
            )

        for index, resource_type in enumerate(["pdf", "blog", "notes"], start=1):
            ReadingResource.objects.create(
                topic=topic,
                title=f"{topic.name} Reading {index}",
                description=f"{topic.name} reading explanation {index}",
                url=f"https://example.com/{slug_fragment(topic.name)}-reading-{index}",
                resource_type=resource_type,
                source_name=f"Source {index}",
                view_count=50000 * index,
                rating=4.1 + (index * 0.1),
                student_helpful_count=8 * index,
                student_not_helpful_count=index,
            )


def slug_fragment(value: str) -> str:
    """Return a short ASCII-safe fragment that works in fake URLs."""
    return value.lower().replace(" ", "")[:8]


class TestModels(BaseTopiqTestCase):
    """Model tests for string output, auto-generated fields, and scoring."""

    def test_semester_str(self):
        """Semester string output should match the semester name."""
        self.assertEqual(str(self.semester), "5th Semester")

    def test_topic_slug_autogenerated(self):
        """Topic save should generate a unique slug automatically."""
        topic = Topic.objects.create(
            subject=self.subject,
            name="Binary Tree Search",
            description="Tree topic",
        )
        self.assertEqual(topic.slug, "binary-tree-search")

    def test_video_thumbnail_autogenerated(self):
        """Saving a video should extract the video ID and thumbnail URL."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="YouTube Parsing Test",
            description="Testing video parsing",
            youtube_url="https://youtube.com/watch?v=abc123",
            duration="12:30",
            duration_seconds=750,
        )
        self.assertEqual(video.youtube_video_id, "abc123")
        self.assertIn("abc123", video.thumbnail_url)

    def test_video_ml_score_calculation(self):
        """ML score calculation should return a positive score for valid metrics."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="ML Score Test",
            description="Testing ML score",
            youtube_url="https://youtube.com/watch?v=score123",
            duration="20:00",
            duration_seconds=1200,
            rating=4.5,
            view_count=500000,
            student_helpful_count=10,
            student_not_helpful_count=2,
        )
        score = video.calculate_ml_score()
        self.assertGreater(score, 0)

    def test_feedback_score_no_division_by_zero(self):
        """Feedback score should safely return zero when no feedback exists."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="Zero Feedback",
            description="No feedback yet",
            youtube_url="https://youtube.com/watch?v=zero123",
            duration="08:00",
            duration_seconds=480,
            student_helpful_count=0,
            student_not_helpful_count=0,
        )
        self.assertEqual(video.feedback_score, 0.0)


class TestViews(BaseTopiqTestCase):
    """View tests covering pages, APIs, sessions, and feedback flows."""

    def test_homepage_loads(self):
        """Homepage should render successfully with project branding."""
        response = self.client.get("/")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Topiq")

    def test_search_with_valid_query(self):
        """Search page should render matching results for a valid query."""
        response = self.client.get("/search/?q=deadlock")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Deadlock")

    def test_search_with_empty_query_redirects(self):
        """Empty search should redirect back to the homepage."""
        response = self.client.get("/search/?q=")
        self.assertEqual(response.status_code, 302)

    def test_api_search_returns_json(self):
        """API search should return a serializable JSON result payload."""
        response = self.client.get("/api/search/?q=deadlock")
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertIn("found", data)
        self.assertIn("videos", data)
        self.assertIn("readings", data)

    def test_bookmark_post_saves_to_session(self):
        """Bookmark endpoint should persist the topic ID in session storage."""
        response = self.client.post(
            "/bookmark/",
            data=json.dumps({"topic_id": self.deadlock_topic.id}),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 200)
        session = self.client.session
        self.assertIn(self.deadlock_topic.id, session.get("bookmarks", []))

    def test_feedback_post_saves_interaction(self):
        """Feedback endpoint should create an interaction and update counts."""
        video = VideoResource.objects.filter(topic=self.deadlock_topic).first()
        original_helpful = video.student_helpful_count

        response = self.client.post(
            "/feedback/",
            data=json.dumps(
                {
                    "resource_type": "video",
                    "resource_id": video.id,
                    "feedback_type": "helpful",
                    "topic_id": self.deadlock_topic.id,
                }
            ),
            content_type="application/json",
        )

        self.assertEqual(response.status_code, 200)
        self.assertTrue(
            StudentInteraction.objects.filter(
                topic=self.deadlock_topic,
                resource_type="video",
                resource_id=video.id,
                interaction_type="helpful",
            ).exists()
        )
        video.refresh_from_db()
        self.assertEqual(video.student_helpful_count, original_helpful + 1)

    def test_ai_chat_without_api_key_returns_fallback(self):
        """AI chat should return a safe fallback reply when no API key exists."""
        with patch.dict("os.environ", {"ANTHROPIC_API_KEY": ""}, clear=False):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain deadlock", "topic_context": "Deadlock"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertIn("reply", data)
        self.assertEqual(data["status"], "error")


class TestRecommender(BaseTopiqTestCase):
    """Recommendation engine tests for query matching and result limits."""

    def setUp(self):
        """Create base fixtures and initialize the recommender."""
        super().setUp()
        self.recommender = ResourceRecommender()

    def test_exact_match(self):
        """Exact topic queries should match the expected topic."""
        result = search_topics("Deadlock")
        self.assertTrue(result["found"])
        self.assertEqual(result["matched_topic_name"], "Deadlock")

    def test_case_insensitive_match(self):
        """Case-insensitive searches should still find the correct topic."""
        result = search_topics("DEADLOCK")
        self.assertTrue(result["found"])

    def test_partial_match(self):
        """Partial phrase matches like 'dead lock' should still resolve."""
        result = search_topics("dead lock")
        self.assertTrue(result["found"])

    def test_synonym_match(self):
        """Keyword-based synonym searches should match binary tree content."""
        result = search_topics("tree data structure")
        self.assertTrue(result["found"])
        self.assertEqual(result["matched_topic_name"], "Binary Tree")

    def test_unknown_topic_returns_not_found(self):
        """Unknown topics should return a safe not-found response."""
        result = search_topics("xyzabcnonexistent123")
        self.assertFalse(result["found"])

    def test_returns_max_3_videos(self):
        """Recommender should never return more than three video results."""
        result = search_topics("Deadlock")
        self.assertLessEqual(len(result["videos"]), 3)

    def test_returns_max_3_readings(self):
        """Recommender should never return more than three reading results."""
        result = search_topics("Deadlock")
        self.assertLessEqual(len(result["readings"]), 3)


class TestManagementCommand(TestCase):
    """Basic smoke tests for the seed_data management command."""

    def test_seed_data_demo_creates_records(self):
        """Demo seed mode should populate a lightweight dataset."""
        call_command("seed_data", "--flush", "--demo")
        self.assertEqual(Semester.objects.count(), 6)
        self.assertEqual(Subject.objects.count(), 8)
        self.assertGreaterEqual(Topic.objects.count(), 6)
        self.assertGreaterEqual(VideoResource.objects.count(), 18)
        self.assertGreaterEqual(ReadingResource.objects.count(), 18)
