"""Integration and feature tests for the Topiq project."""

from __future__ import annotations

import json
from unittest.mock import Mock, patch

import requests
from django.core.management import call_command
from django.test import Client, TestCase

from website.models import (
    ReadingResource,
    Semester,
    StudentInteraction,
    Subject,
    Topic,
    VideoResource,
)
from website.recommender import ResourceRecommender, search_topics


class BaseTopiqTestCase(TestCase):
    """Shared fixture creation helpers for Topiq tests."""

    def setUp(self):
        """Create a reusable subject/topic/resource graph for tests."""
        self.client = Client()
        self.semester = Semester.objects.create(name="5th Semester", order=5)
        self.subject = Subject.objects.create(
            semester=self.semester,
            name="Operating System",
            code="CS301",
            description="Operating system fundamentals.",
        )
        self.deadlock_topic = Topic.objects.create(
            subject=self.subject,
            name="Deadlock",
            description="Deadlock concepts and resource allocation.",
            tags="deadlock, coffman conditions, banker algorithm, mutual exclusion",
            search_keywords="dead lock banker algorithm circular wait",
        )
        self.binary_tree_topic = Topic.objects.create(
            subject=Subject.objects.create(
                semester=Semester.objects.create(name="3rd Semester", order=3),
                name="Data Structures",
                code="CS201",
                description="Data structures course.",
            ),
            name="Binary Tree",
            description="Binary trees and traversals.",
            tags="binary tree, bst, tree traversal",
            search_keywords="tree data structure binary search tree",
        )
        self._create_resources_for_topic(self.deadlock_topic)
        self._create_resources_for_topic(self.binary_tree_topic)

    def _create_resources_for_topic(self, topic: Topic):
        """Create three videos and three readings for the given topic."""
        for index, difficulty in enumerate(["beginner", "intermediate", "advanced"], start=1):
            VideoResource.objects.create(
                topic=topic,
                title=f"{topic.name} Video {index}",
                description=f"{topic.name} video explanation {index}",
                youtube_url=f"https://youtube.com/watch?v={slug_fragment(topic.name)}v{index}",
                duration=f"{10 + index}:0{index}",
                duration_seconds=(10 + index) * 60 + index,
                difficulty_level=difficulty,
                view_count=100000 * index,
                rating=4.2 + (index * 0.1),
                student_helpful_count=10 * index,
                student_not_helpful_count=index,
            )

        for index, resource_type in enumerate(["pdf", "blog", "notes"], start=1):
            ReadingResource.objects.create(
                topic=topic,
                title=f"{topic.name} Reading {index}",
                description=f"{topic.name} reading explanation {index}",
                url=f"https://example.com/{slug_fragment(topic.name)}-reading-{index}",
                resource_type=resource_type,
                source_name=f"Source {index}",
                view_count=50000 * index,
                rating=4.1 + (index * 0.1),
                student_helpful_count=8 * index,
                student_not_helpful_count=index,
            )


def slug_fragment(value: str) -> str:
    """Return a short ASCII-safe fragment that works in fake URLs."""
    return value.lower().replace(" ", "")[:8]


class TestModels(BaseTopiqTestCase):
    """Model tests for string output, auto-generated fields, and scoring."""

    def test_semester_str(self):
        """Semester string output should match the semester name."""
        self.assertEqual(str(self.semester), "5th Semester")

    def test_topic_slug_autogenerated(self):
        """Topic save should generate a unique slug automatically."""
        topic = Topic.objects.create(
            subject=self.subject,
            name="Binary Tree Search",
            description="Tree topic",
        )
        self.assertEqual(topic.slug, "binary-tree-search")

    def test_video_thumbnail_autogenerated(self):
        """Saving a video should extract the video ID and thumbnail URL."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="YouTube Parsing Test",
            description="Testing video parsing",
            youtube_url="https://youtube.com/watch?v=abc123",
            duration="12:30",
            duration_seconds=750,
        )
        self.assertEqual(video.youtube_video_id, "abc123")
        self.assertIn("abc123", video.thumbnail_url)

    def test_video_ml_score_calculation(self):
        """ML score calculation should return a positive score for valid metrics."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="ML Score Test",
            description="Testing ML score",
            youtube_url="https://youtube.com/watch?v=score123",
            duration="20:00",
            duration_seconds=1200,
            rating=4.5,
            view_count=500000,
            student_helpful_count=10,
            student_not_helpful_count=2,
        )
        score = video.calculate_ml_score()
        self.assertGreater(score, 0)

    def test_feedback_score_no_division_by_zero(self):
        """Feedback score should safely return zero when no feedback exists."""
        video = VideoResource.objects.create(
            topic=self.deadlock_topic,
            title="Zero Feedback",
            description="No feedback yet",
            youtube_url="https://youtube.com/watch?v=zero123",
            duration="08:00",
            duration_seconds=480,
            student_helpful_count=0,
            student_not_helpful_count=0,
        )
        self.assertEqual(video.feedback_score, 0.0)


class TestViews(BaseTopiqTestCase):
    """View tests covering pages, APIs, sessions, and feedback flows."""

    def test_homepage_loads(self):
        """Homepage should render successfully with project branding."""
        response = self.client.get("/")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Topiq")

    def test_search_with_valid_query(self):
        """Search page should render matching results for a valid query."""
        response = self.client.get("/search/?q=deadlock")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Deadlock")
        self.assertContains(response, "Open on YouTube")

    def test_search_with_empty_query_redirects(self):
        """Empty search should redirect back to the homepage."""
        response = self.client.get("/search/?q=")
        self.assertEqual(response.status_code, 302)

    def test_api_search_returns_json(self):
        """API search should return a serializable JSON result payload."""
        response = self.client.get("/api/search/?q=deadlock")
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertIn("found", data)
        self.assertIn("videos", data)
        self.assertIn("readings", data)

    def test_bookmark_post_saves_to_session(self):
        """Bookmark endpoint should persist the topic ID in session storage."""
        response = self.client.post(
            "/bookmark/",
            data=json.dumps({"topic_id": self.deadlock_topic.id}),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 200)
        session = self.client.session
        self.assertIn(self.deadlock_topic.id, session.get("bookmarks", []))

    def test_feedback_post_saves_interaction(self):
        """Feedback endpoint should create an interaction and update counts."""
        video = VideoResource.objects.filter(topic=self.deadlock_topic).first()
        original_helpful = video.student_helpful_count

        response = self.client.post(
            "/feedback/",
            data=json.dumps(
                {
                    "resource_type": "video",
                    "resource_id": video.id,
                    "feedback_type": "helpful",
                    "topic_id": self.deadlock_topic.id,
                }
            ),
            content_type="application/json",
        )

        self.assertEqual(response.status_code, 200)
        self.assertTrue(
            StudentInteraction.objects.filter(
                topic=self.deadlock_topic,
                resource_type="video",
                resource_id=video.id,
                interaction_type="helpful",
            ).exists()
        )
        video.refresh_from_db()
        self.assertEqual(video.student_helpful_count, original_helpful + 1)

    def test_ai_chat_without_api_key_returns_fallback(self):
        """AI chat should return a safe fallback reply when no API key exists."""
        with patch.dict("os.environ", {"AI_PROVIDER": "groq", "GROQ_API_KEY": "", "ANTHROPIC_API_KEY": ""}, clear=False):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain deadlock", "topic_context": "Deadlock"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertIn("reply", data)
        self.assertEqual(data["status"], "error")

    @patch("website.views.requests.post")
    def test_ai_chat_uses_groq_by_default_when_key_exists(self, mock_post):
        """AI chat should default to Groq when a Groq key is configured."""
        mock_response = Mock()
        mock_response.raise_for_status.return_value = None
        mock_response.json.return_value = {
            "choices": [{"message": {"content": "Python programming is the process of writing instructions in Python."}}]
        }
        mock_post.return_value = mock_response

        with patch.dict(
            "os.environ",
            {"GROQ_API_KEY": "test-groq-key", "GROQ_MODEL": "llama-3.1-8b-instant", "ANTHROPIC_API_KEY": ""},
            clear=False,
        ):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain python programming", "topic_context": "Python"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "ok")
        self.assertEqual(
            mock_post.call_args.kwargs["json"]["model"],
            "llama-3.1-8b-instant",
        )
        self.assertEqual(
            mock_post.call_args.args[0],
            "https://api.groq.com/openai/v1/chat/completions",
        )

    @patch("website.views.requests.post")
    def test_ai_chat_uses_configurable_anthropic_model(self, mock_post):
        """AI chat should use the configured Anthropic model alias."""
        mock_response = Mock()
        mock_response.raise_for_status.return_value = None
        mock_response.json.return_value = {"content": [{"text": "Python is a programming language."}]}
        mock_post.return_value = mock_response

        with patch.dict(
            "os.environ",
            {
                "AI_PROVIDER": "anthropic",
                "ANTHROPIC_API_KEY": "test-key",
                "ANTHROPIC_MODEL": "claude-3-5-haiku-latest",
                "GROQ_API_KEY": "",
            },
            clear=False,
        ):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain python programming", "topic_context": "Python"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "ok")
        self.assertEqual(mock_post.call_args.kwargs["json"]["model"], "claude-3-5-haiku-latest")

    @patch("website.views.requests.post")
    def test_ai_chat_returns_model_hint_on_bad_request(self, mock_post):
        """AI chat should show a helpful message when Anthropic rejects the model."""
        mock_response = Mock()
        mock_response.text = '{"error":{"message":"model not found"}}'
        mock_response.json.return_value = {"error": {"message": "model not found"}}
        error = requests.exceptions.HTTPError("400 Client Error", response=mock_response)
        mock_response.raise_for_status.side_effect = error
        mock_post.return_value = mock_response

        with patch.dict(
            "os.environ",
            {"AI_PROVIDER": "anthropic", "ANTHROPIC_API_KEY": "test-key", "GROQ_API_KEY": ""},
            clear=False,
        ):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain python programming", "topic_context": "Python"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "error")
        self.assertIn("ANTHROPIC_MODEL", response.json()["reply"])

    @patch("website.views.requests.post")
    def test_ai_chat_returns_groq_key_hint_on_auth_error(self, mock_post):
        """AI chat should show a Groq-specific key hint on auth failures."""
        mock_response = Mock()
        mock_response.text = '{"error":{"message":"Unauthorized"}}'
        mock_response.json.return_value = {"error": {"message": "Unauthorized"}}
        error = requests.exceptions.HTTPError("401 Unauthorized", response=mock_response)
        mock_response.raise_for_status.side_effect = error
        mock_post.return_value = mock_response

        with patch.dict("os.environ", {"AI_PROVIDER": "groq", "GROQ_API_KEY": "test-key"}, clear=False):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain python programming", "topic_context": "Python"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "error")
        self.assertIn("GROQ_API_KEY", response.json()["reply"])

    @patch("website.views.requests.post")
    def test_ai_chat_returns_credit_message_when_balance_is_low(self, mock_post):
        """AI chat should explain when Anthropic billing credits are exhausted."""
        mock_response = Mock()
        mock_response.text = '{"error":{"message":"Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits."}}'
        mock_response.json.return_value = {
            "error": {
                "message": "Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits."
            }
        }
        error = requests.exceptions.HTTPError("400 Client Error", response=mock_response)
        mock_response.raise_for_status.side_effect = error
        mock_post.return_value = mock_response

        with patch.dict(
            "os.environ",
            {"AI_PROVIDER": "anthropic", "ANTHROPIC_API_KEY": "test-key", "GROQ_API_KEY": ""},
            clear=False,
        ):
            response = self.client.post(
                "/api/chat/",
                data=json.dumps({"message": "Explain python programming", "topic_context": "Python"}),
                content_type="application/json",
            )

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "error")
        self.assertIn("credits are exhausted", response.json()["reply"])


class TestRecommender(BaseTopiqTestCase):
    """Recommendation engine tests for query matching and result limits."""

    def setUp(self):
        """Create base fixtures and initialize the recommender."""
        super().setUp()
        self.recommender = ResourceRecommender()

    def test_exact_match(self):
        """Exact topic queries should match the expected topic."""
        result = search_topics("Deadlock")
        self.assertTrue(result["found"])
        self.assertEqual(result["matched_topic_name"], "Deadlock")

    def test_case_insensitive_match(self):
        """Case-insensitive searches should still find the correct topic."""
        result = search_topics("DEADLOCK")
        self.assertTrue(result["found"])

    def test_partial_match(self):
        """Partial phrase matches like 'dead lock' should still resolve."""
        result = search_topics("dead lock")
        self.assertTrue(result["found"])

    def test_synonym_match(self):
        """Keyword-based synonym searches should match binary tree content."""
        result = search_topics("tree data structure")
        self.assertTrue(result["found"])
        self.assertEqual(result["matched_topic_name"], "Binary Tree")

    def test_unknown_topic_returns_not_found(self):
        """Unknown topics should return a safe not-found response."""
        result = search_topics("xyzabcnonexistent123")
        self.assertFalse(result["found"])

    def test_returns_max_3_videos(self):
        """Recommender should never return more than three video results."""
        result = search_topics("Deadlock")
        self.assertLessEqual(len(result["videos"]), 3)

    def test_returns_max_3_readings(self):
        """Recommender should never return more than three reading results."""
        result = search_topics("Deadlock")
        self.assertLessEqual(len(result["readings"]), 3)


class TestManagementCommand(TestCase):
    """Basic smoke tests for the seed_data management command."""

    def test_seed_data_demo_creates_records(self):
        """Demo seed mode should populate a lightweight dataset."""
        call_command("seed_data", "--flush", "--demo")
        self.assertEqual(Semester.objects.count(), 6)
        self.assertEqual(Subject.objects.count(), 8)
        self.assertGreaterEqual(Topic.objects.count(), 6)
        self.assertGreaterEqual(VideoResource.objects.count(), 18)
        self.assertGreaterEqual(ReadingResource.objects.count(), 18)

    def test_seed_data_uses_working_youtube_search_links(self):
        """Seeded demo video records should use safe YouTube search URLs."""
        call_command("seed_data", "--flush", "--demo")
        video = VideoResource.objects.first()
        self.assertIsNotNone(video)
        self.assertIn("youtube.com/results?search_query=", video.youtube_url)
        self.assertIsNone(video.youtube_video_id)
